# Generated by Django 5.1.4 on 2025-01-24 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyentry',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='dailyentry',
            name='user',
        ),
    ]
